apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  labels:
    app: kafka-producer-etc
spec:
  ports:
  - port: 8060
    targetPort: 8060
    protocol: TCP
    name: http
  selector:
    app: kafka-producer-etc
  type: NodePort
