server:
  port: 8060
spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BROKER}:${KAFKA_BROKER_PORT}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer           
kafka:
  topic-name: ${TOPIC_NAME}
  message-per-request: ${MESSAGE_PER_REQUEST}